version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.3.0
  featurepeek: featurepeek/ping@dev:gcr
workflows:
  build-and-push-image:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: myContext
          image: nteract
      - featurepeek/ping_featurepeek:
          requires:
            - gcp-gcr/build_and_push_image
          image: nteract
          env: dev
