version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.3.0
  featurepeek: featurepeek/ping@0.0.2
workflows:
  build-and-push-image:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: nteract
      - featurepeek/ping_featurepeek:
          requires:
            - gcp-gcr/build-and-push-image
          image: nteract
          # env: dev
